<Project>
	<PropertyGroup Condition="'$(MSBuildProjectName)' == 'ComputeSharp' or '$(MSBuildProjectName)' == 'ComputeSharp.Core'">
		<IsPackagedProject>false</IsPackagedProject>
	</PropertyGroup>
	<ItemGroup Condition="'$(MSBuildProjectName)' == 'ComputeSharp.Core'">
		<InternalsVisibleTo Include="Ukiyoe.ComputeSharp, PublicKey=$(AssemblySignPublicKey)" />
	</ItemGroup>
</Project>
