<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AssemblyName>Ukiyoe.Tests</AssemblyName>
    <RootNamespace>Ukiyoe.Tests</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ukiyoe\Ukiyoe.csproj" SetConfiguration="Configuration=$(Configuration)" SetPlatform="Platform=x64">
      <AdditionalProperties Condition="'$(BuildingSolutionFile)' != 'true'">SkipPluginDeploy=true</AdditionalProperties>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="SharpGen.Runtime">
      <HintPath>$(YMM4DirPath)SharpGen.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="SharpGen.Runtime.COM">
      <HintPath>$(YMM4DirPath)SharpGen.Runtime.COM.dll</HintPath>
    </Reference>
    <Reference Include="Vortice.Direct2D1">
      <HintPath>$(YMM4DirPath)Vortice.Direct2D1.dll</HintPath>
    </Reference>
    <Reference Include="Vortice.Direct3D11">
      <HintPath>$(YMM4DirPath)Vortice.Direct3D11.dll</HintPath>
    </Reference>
    <Reference Include="Vortice.DirectX">
      <HintPath>$(YMM4DirPath)Vortice.DirectX.dll</HintPath>
    </Reference>
    <Reference Include="Vortice.DXGI">
      <HintPath>$(YMM4DirPath)Vortice.DXGI.dll</HintPath>
    </Reference>
    <Reference Include="Vortice.Mathematics">
      <HintPath>$(YMM4DirPath)Vortice.Mathematics.dll</HintPath>
    </Reference>
    <Reference Include="YukkuriMovieMaker.Plugin">
      <HintPath>$(YMM4DirPath)YukkuriMovieMaker.Plugin.dll</HintPath>
    </Reference>
    <Reference Include="YukkuriMovieMaker.Controls">
      <HintPath>$(YMM4DirPath)YukkuriMovieMaker.Controls.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <Import Project="..\Ukiyoe\ComputeWeave.Reference.props" />

</Project>
